apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 'megabites/portal-cultura'
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/megabites/portal-cultura:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
################
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/megabites/portal-cultura:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: 'portal-cultura'
        chartPath: 'charts/portal-cultura'
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/megabites/portal-cultura'
          image.tag: '{{.DIGEST_HEX}}'
